In [1]:
import numpy as np

In [2]:
#Basics
a = np.array([1,2,3,4])#create an array

a+1 #scaler addition

array([2, 3, 4, 5])

In [3]:
a ** 2

array([ 1,  4,  9, 16])

In [4]:
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [5]:
a * b

array([ 2.,  4.,  6.,  8.])

In [6]:
#matrix multiplication
c = np.diag([1,2,3,4])
print(c * c)
print("*******************************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*******************************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [7]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

a==b

array([ True,  True,  True,  True], dtype=bool)

In [8]:
a>b

array([False, False, False, False], dtype=bool)

In [9]:
#array_wise comparision
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
c = np.array([1,2,3,4])

np.array_equal(a,b)


False

In [10]:
#matrix multiplication
c = np.diag([1,2,3,4])

print(c*c)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [11]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [12]:
np.exp(a)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [13]:
a = np.arange(4)

a + np.array([1,2])



ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [14]:
#Basic reductions
x = np.array([1,2,3,4])
np.sum(x)

10

In [15]:
print(np.sum.__doc__)


    Sum of array elements over a given axis.

    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.

        .. versionadded:: 1.7.0

        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In that case, if `a` is signed then the platform integer
        is used while if `a` is unsigned then an unsigned integer of the
        same precision

In [16]:
 x = np.array([1,3,5])
x.min()

1

In [18]:
print(np.min.__doc__)


    Return the minimum of an array or minimum along an axis.

    Parameters
    ----------
    a : array_like
        Input data.
    axis : None or int or tuple of ints, optional
        Axis or axes along which to operate.  By default, flattened input is
        used.

        .. versionadded:: 1.7.0

        If this is a tuple of ints, the minimum is selected over multiple axes,
        instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternative output array in which to place the result.  Must
        be of the same shape and buffer length as the expected output.
        See `doc.ufuncs` (Section "Output arguments") for more details.

    keepdims : bool, optional
        If this is set to True, the axes which are reduced are left
        in the result as dimensions with size one. With this option,
        the result will broadcast correctly against the input array.

        If the default value is passed, then `keepdims` will not be
       