In [5]:
#first import numpy
import numpy as np


In [6]:
a = np.array([0,1,2,3])
print(a)

[0 1 2 3]


In [7]:
print(np.arange(20))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [8]:
#time efficient
L = range(1000)
%timeit [i**2 for i in L]

462 µs ± 27.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
a = np.arange(1000)
%timeit a**2

2.24 µs ± 17.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
#creating a numpy array
#1-D
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [11]:
#find dimensions
a.ndim

1

In [12]:
#shaoe
a.shape

(4,)

In [13]:
#length
len(a)

4

In [14]:
#2-D
b = np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
b.ndim

2

In [16]:
b.shape

(2, 3)

In [17]:
len(b)#return the length of first dimension

2

In [18]:
#3-D
c = np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
c

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]]])

In [19]:
c.ndim

3

In [20]:
c.shape

(2, 2, 2)

In [21]:
#1-D called vector
#2-D called matrix
#n-D called Tensor


In [22]:
a = np.arange(100)

In [23]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [24]:
b = np.arange(2,100,2)

In [25]:
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [26]:
#ones 
a = np.ones((4,2),int,3)
print(a)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [27]:
#zeros
a = np.zeros((3,3),int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [28]:
print(np.ones.__doc__)


    Return a new array of given shape and type, filled with ones.

    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.

    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.

    See Also
    --------
    zeros, ones_like

    Examples
    --------
    >>> np.ones(5)
    array([ 1.,  1.,  1.,  1.,  1.])

    >>> np.ones((5,), dtype=np.int)
    array([1, 1, 1, 1, 1])

    >>> np.ones((2, 1))
    array([[ 1.],
           [ 1.]])

    >>> s = (2,2)
    >>> np.ones(s)
    array([[ 1.,  1.],
           [ 1.,  1.]])

    


In [29]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [30]:
print(np.eye.__doc__)



    Return a 2-D array with ones on the diagonal and zeros elsewhere.

    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.

    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.

    See Also
    --------
    identity : (almost) equivalent function
    diag : diagonal 2-D array from a 1-D array specified by the user.

    Examples
    --------
    >>> np.eye(2, dtype=int)
    array([[1, 0],
           [0, 1]])
    >>> np.eye(3, k=1)
    array([[ 0.,  1.,  0.],
           [ 0.,  0.,  1.],
   

In [31]:
np.eye(3,dtype=int,k=2)

array([[0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [32]:
#digonal matrix
a = np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [33]:
print(np.diag.__doc__)


    Extract a diagonal or construct a diagonal array.

    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.

    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.

    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.

    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the flattened input as a diagonal.
    trace : Sum along diagonals.
    triu : Upper tri

In [34]:
print(np.diag(a))

[1 2 3 4]


In [35]:
#create random vector

print(np.random.rand(10))

[ 0.55532231  0.9072086   0.10175667  0.26334395  0.04046052  0.43125615
  0.80935629  0.37797742  0.05555239  0.89770109]


In [36]:
print(np.random.rand.__doc__)


        rand(d0, d1, ..., dn)

        Random values in a given shape.

        Create an array of the given shape and populate it with
        random samples from a uniform distribution
        over ``[0, 1)``.

        Parameters
        ----------
        d0, d1, ..., dn : int, optional
            The dimensions of the returned array, should all be positive.
            If no argument is given a single Python float is returned.

        Returns
        -------
        out : ndarray, shape ``(d0, d1, ..., dn)``
            Random values.

        See Also
        --------
        random

        Notes
        -----
        This is a convenience function. If you want an interface that
        takes a shape-tuple as the first argument, refer to
        np.random.random_sample .

        Examples
        --------
        >>> np.random.rand(3,2)
        array([[ 0.14022471,  0.96360618],  #random
               [ 0.37601032,  0.25528411],  #random
               [ 0.49313049,  0.949098

In [37]:
#slicing
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
print(a[1:8:2])

[1 3 5 7]


In [39]:
a[5:]=10

In [40]:
print(a)

[ 0  1  2  3  4 10 10 10 10 10]


In [41]:
a = np.random.randint(0,20,15)
a

array([19, 15,  6,  1,  0, 16,  0,  6, 14,  0,  7,  2,  1, 13,  3])

In [42]:
mask = (a%2 == 0)

In [43]:
extracted_from_a = a[mask]
extracted_from_a

array([ 6,  0, 16,  0,  6, 14,  0,  2])

In [44]:
#load data from a file
data = np.loadtxt('populations.txt')

In [45]:
print(data)

[[  1900.  30000.   4000.  48300.]
 [  1901.  47200.   6100.  48200.]
 [  1902.  70200.   9800.  41500.]
 [  1903.  77400.  35200.  38200.]
 [  1904.  36300.  59400.  40600.]
 [  1905.  20600.  41700.  39800.]
 [  1906.  18100.  19000.  38600.]
 [  1907.  21400.  13000.  42300.]
 [  1908.  22000.   8300.  44500.]
 [  1909.  25400.   9100.  42100.]
 [  1910.  27100.   7400.  46000.]
 [  1911.  40300.   8000.  46800.]
 [  1912.  57000.  12300.  43800.]
 [  1913.  76600.  19500.  40900.]
 [  1914.  52300.  45700.  39400.]
 [  1915.  19500.  51100.  39000.]
 [  1916.  11200.  29700.  36700.]
 [  1917.   7600.  15800.  41800.]
 [  1918.  14600.   9700.  43300.]
 [  1919.  16200.  10100.  41300.]
 [  1920.  24700.   8600.  47300.]]


In [46]:
year,hares,lynxes,carrots = data.T

In [47]:
print(year)

[ 1900.  1901.  1902.  1903.  1904.  1905.  1906.  1907.  1908.  1909.
  1910.  1911.  1912.  1913.  1914.  1915.  1916.  1917.  1918.  1919.
  1920.]


In [48]:
print(hares)

[ 30000.  47200.  70200.  77400.  36300.  20600.  18100.  21400.  22000.
  25400.  27100.  40300.  57000.  76600.  52300.  19500.  11200.   7600.
  14600.  16200.  24700.]


In [49]:
print(lynxes)

[  4000.   6100.   9800.  35200.  59400.  41700.  19000.  13000.   8300.
   9100.   7400.   8000.  12300.  19500.  45700.  51100.  29700.  15800.
   9700.  10100.   8600.]


In [50]:
print(carrots)

[ 48300.  48200.  41500.  38200.  40600.  39800.  38600.  42300.  44500.
  42100.  46000.  46800.  43800.  40900.  39400.  39000.  36700.  41800.
  43300.  41300.  47300.]


In [59]:
populations = data[:,1:]
print(populations)

[[ 30000.   4000.  48300.]
 [ 47200.   6100.  48200.]
 [ 70200.   9800.  41500.]
 [ 77400.  35200.  38200.]
 [ 36300.  59400.  40600.]
 [ 20600.  41700.  39800.]
 [ 18100.  19000.  38600.]
 [ 21400.  13000.  42300.]
 [ 22000.   8300.  44500.]
 [ 25400.   9100.  42100.]
 [ 27100.   7400.  46000.]
 [ 40300.   8000.  46800.]
 [ 57000.  12300.  43800.]
 [ 76600.  19500.  40900.]
 [ 52300.  45700.  39400.]
 [ 19500.  51100.  39000.]
 [ 11200.  29700.  36700.]
 [  7600.  15800.  41800.]
 [ 14600.   9700.  43300.]
 [ 16200.  10100.  41300.]
 [ 24700.   8600.  47300.]]


In [60]:
populations.std(axis=0)

array([ 20897.90645809,  16254.59153691,   3322.50622558])

In [61]:
#which species has the highest population  each year
np.argmax(populations,axis = 1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])